=== jasperla/dot.files/.config/openbox/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
     xml Schema for the openbox windowmanager menu file

     Changes:
     Don Aug 14 21:10:27 CEST 2003 - pch(a)myzel.net
         split from rc3.xsd
     Mon Sep  8 12:33:57 CEST 2003 - pch(a)myzel.net
         up to beta1
     Die Sep 16 21:22:59 CEST 2003 - pch(a)myzel.net
         use a namespace
     Fri Sep 19 14:36:33 EDT 2003 - xor(a)orodu.net
         use openbox.org for namespace
     Mon Sep 22 02:42:10 EDT 2003 - xor(a)orodu.net
         fix some capitalization
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://openbox.org/"
    xmlns:ob="http://openbox.org/"
    elementFormDefault="qualified">
    <!--
         root node
      -->
    <xs:element name="openbox_menu">
        <xs:complexType mixed="false">
            <xs:sequence maxOccurs="unbounded" minOccurs="1">
                <xs:element name="menu" type="ob:menu"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--
         complex types
      -->
    <xs:complexType name="menu">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element maxOccurs="unbounded" minOccurs="0" name="menu" type="ob:menu"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="item" type="ob:item"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="separator" type="ob:empty"/>
        </xs:choice>
        <xs:attribute name="label" type="xs:string" use="optional"/>
        <xs:attribute name="execute" type="xs:string" use="optional"/>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="empty">
        <xs:complexContent>
            <xs:restriction base="xs:anyType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="item">
        <xs:sequence>
            <xs:element minOccurs="0" name="action">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="execute" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="name" type="ob:actionname" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="label" type="xs:string" use="required"/>
    </xs:complexType>
    <!--
         simple types / restrictions
      -->
    <xs:simpleType name="actionname">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Execute"/>
            <xs:enumeration value="Restart"/>
            <xs:enumeration value="Reconfigure"/>
            <xs:enumeration value="Exit"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== jasperla/dot.files/.config/openbox/menu.xml
<?xml version="1.0" encoding="UTF-8"?>

<openbox_menu xmlns="http://openbox.org/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://openbox.org/
                file:///usr/local/share/openbox/menu.xsd">

<menu id="ssh-menu" label="ssh (X11) to...">
<!--
  <item label="lychee">
    <action name="Execute"><execute>aterm -e ssh lychee</execute></action>
  </item>
  <item label="cvs">
    <action name="Execute"><execute>aterm -e ssh cvs</execute></action>
  </item>
  <item label="opi">
    <action name="Execute"><execute>aterm -e ssh opi</execute></action>
  </item>
  <item label="fire">
    <action name="Execute"><execute>aterm -e ssh fire</execute></action>
  </item>
-->
  <item label="namak">
    <action name="Execute"><execute>aterm -e ssh -Y namak</execute></action>
  </item>
</menu>

<menu id="apps-menu" label="Applications">
  <item label="Xterm">
    <action name="Execute"><execute>xterm -bg black -fg grey -fn fixed</execute></action>
  </item>
  <item label="Gaim">
    <action name="Execute"><execute>gaim</execute></action>
  </item>
  <item label="Quark">
    <action name="Execute"><execute>strange-quark</execute></action>
  </item>
</menu>

<menu id="root-menu" label="OB3@OBSD5">
  <menu id="ssh-menu" />
  <menu id="apps-menu" />
  <separator />
  <menu id="client-list-menu" />
  <separator />
  <item label="ObConf">
    <action name="Execute"><execute>obconf</execute></action>
  </item>
  <item label="Reconfigure">
    <action name="Reconfigure" />
  </item>
  <separator />
  <item label="Exit">
    <action name="Exit" />
  </item>
</menu>

</openbox_menu>
